### ISSUE TITLE
Retrieve user credit balance and validate user credential

### ISSUE THREAD

**Issue by ThinhVu** [quadient/data-services-client-dotnet#40]
Hi guys, I have some issues when using this library.
I read throughout of the source code but couldn't found any way to get user credit balance information.
And there is no simple way to check whether user credential is valid, an error only return lately when we call Execute method. Am I wrong?
I found this endpoint (https://data.quadientcloud.com/oauth/token) in document page. It can be use for user credential validation.

**Comment by ThinhVu** [comment]
Thank you for your response.

**Comment by kaspersorensen** [comment]
Hi @ThinhVu I just wanted to let you know that we have fixed this issue, and you can now call "IClient.GetAuthenticatedUser()` to get to things like credit balance and validating user credentials. The release is being done now.
